export interface AcuityParams {
  max?: number,
  minDate?: Date,
  maxDate?: Date,
  calendarID?: number,
  appointmentTypeId?: number,
  canceled: boolean,
  firstName?: string,
  lastName?: string,
  email?: string,
  phone?: string,
  fieldID?: string,
  excludeForms?: boolean,
  direction: 'ASC' | 'DESC'
}

export interface AcuityAppointment {
  id?: number,
  firstName?: string,
  lastName?: string,
  phone?: string,
  email?: string,
  date?: string | Date,
  datetime?: Date,
  time?: string,
  endTime?: string,
  price?: string | number,
  paid?: string | boolean,
  type?: any,
  appointmentTypeID?: number,
  addonIDs?: number[],
  classID?: number,
  duration?: string,
  calendar?: string,
  calendarID?: number,
  canClientCancel?: false,
  canClientReschedule?: false,
  location?: string,
  confirmationPage?: string,
  formsText?: string,
  notes?: string,
  timezone?: any,
  forms?: object[],
  labels?: object[]
}
